Insert into Company(PublisherName,DeveloperName,Country,GameId)
Values('Niantic Labs','Niantic Labs','USA',1),
	   ('Sony Computer Entertainment','Square','Japan',2),
	   ('Blizzard Entertainment','Blizzard Entertainment','USA',3),
	   ('LucasArts','LucasArts','USA',4),
	   ('Electronic Arts','Criterion Games','USA',5),
	   ('Interplay','Black Isle Studios','USA',6),
	   ('TobyFox','TobyFox','USA',7),
	   ('THQ','Riot Games','USA',8),
	   ('Electronic Arts','Maxis','USA',9),
	   ('Playdead','Playdead','Denmark',10),
	   ('Nintendo','Nintendo','Japan',11),
	   ('Electronic Arts','Looking Glass','USA',12),
	   ('Rockstar Games','Rockstar North','USA',13),
	   ('SEGA','Atlus','Japan',14),
	   ('Nintendo','Nintendo','Japan',15),
	   ('Konami','Konami TYO','Japan',16),
	   ('Electronic Arts','DICE (Digital Illusions CE)','USA',17),
	   ('Electronic Arts','Respawn Entertainment','USA',18),
	   ('Valve','Valve','USA',19),
	   ('Mossmouth','Mossmouth','USA',20),
	   ('Nintendo','Coleco','Japan',21),
	   ('Valve','Valve','USA',22),
	   ('Electronic Arts','The Sims Studio','USA',23),
	   ('Sony Computer Entertainment','Naughty Dog Software','Japan',24),
	   ('Activision Blizzard','Activision Blizzard','USA',24),
	   ('Activision','Infinity Ward','USA',26),
	   ('Warner Bros. Interactive','Rocksteady Studios','USA',27),
	   ('Electronic Arts','BioWare','USA',28),
	   ('Nintendo','Nintendo','Japan',29),
	   ('Konami','Konami TYO','Japan',30),
	   ('Hasbro Interactive','Supersonic Software','Japan',31),
	   ('Warner Bros. Interactive','NetherRealm Studios','USA',32),
	   ('Blizzard Entertainment','Blizzard Entertainment','USA',33),
	   ('Microsoft','BCrystal Dynamics','USA',34),
	   ('Williams Entertainment Inc','Williams Entertainment Inc','USA',35),
	   ('Electronic Arts','Criterion Games','USA',36),
	   ('Electronic Arts','Electronic Arts','USA',37),
	   ('Sony Computer Entertainment','Santa Monica Studio','Japan',38),
	   ('Ubisoft','Ubisoft Montreal','France',39),
	   ('Ubisoft','Ubisoft Montreal','France',40),
	   ('Ubisoft','Ubisoft Paris','France',41),
	   ('Ubisoft','Massive Entertainment','France',42),
	   ('Sony Computer Entertainment','Insomniac Games','Japan',43),
	   ('PUBG Corp.','Bluehole Studio','Korea',44),
	   ('Electronic Arts','Respawn Entertainment','USA',45),
	   ('Longbow Digital Arts','Longbow Digital Arts','Canada',46),
	   ('Virgin Interactive','Eurocom','USA',47),
	   ('Ubisoft','Ubisoft Montreal','France',48),
	   ('Ubisoft','Ubisoft Quebec City','France',49),
	   ('Imangi','Imangi','USA',50),
	   ('Imangi','Imangi','USA',51),
	   ('Sybo Games','Kiloo ApS','Denmark',52),
	   ('Chillingo','Rovio','USA',53),
	   ('Electronic Arts','EA Canada','USA',54),
	   ('Capcom','Capcom R&D Divison 1','Japan',55),
	   ('SEGA','SEGA-AM1','Japan',56),
	   ('Rockstar Games','	Rockstar Studios','USA',57),
	   ('Electronic Arts','EA Canada','USA',58),
	   ('SEGA','SEGA-AM2','Japan',59),
	   ('Mojang','Mojang','Sweden',60),
	   ('Fireproof Games','	Fireproof Games','UK',61),
	   ('Snowman','Snowman','USA',62),
	   ('Supercell','Supercell','Finland',63),
	   ('Gameloft','Gameloft','France',64),
	   ('Miniclip','Appsomniacs LLC','Spain',65),
	   ('Gameloft','Gameloft','France',66),
	   ('Ubisoft','Ubisoft Casablanca','France',67),
	   ('Microsoft','Bungie Software','USA',68),
	   ('King','King','Malta',69),
	   ('Capcom','Capcom','Japan',70)

	   	Select * From Company
	   